author: "Jérôme Sautret <jerome.sautret at process-one.net>"
category: "log"
summary: "Logging chat messages in text files"
home: "https://github.com/tpphu/ejabberd-contrib/tree/master/"
url: "git@github.com:tpphu/ejabberd-contrib.git"
