author: "Thiago Rocha Camargo <rochacamargothiago at gmail.com>"
category: "statistics"
summary: "Publishes Statistics via statsd/grafite"
home: "https://github.com/tpphu/ejabberd-contrib/tree/master/"
url: "git@github.com:tpphu/ejabberd-contrib.git"
