author: "Holger Weiss <holger at zedat.fu-berlin.de>"
category: "log"
summary: "Log one line per message transmission in text file"
home: "https://github.com/tpphu/ejabberd-contrib/tree/master/"
url: "git@github.com:tpphu/ejabberd-contrib.git"
