author: "Igor Goryachev <igor at goryachev.org>"
category: "data"
summary: "Publish user presence information in the web"
home: "https://github.com/tpphu/ejabberd-contrib/tree/master/"
url: "git@github.com:tpphu/ejabberd-contrib.git"
