author: "Holger Weiss <holger at zedat.fu-berlin.de>"
category: "policy"
summary: "Prevent OMEMO sessions from being established"
home: "https://github.com/tpphu/ejabberd-contrib/tree/master/"
url: "git@github.com:tpphu/ejabberd-contrib.git"
