author: "Mickael Remond <mremond at process-one.net>"
category: "log"
summary: "Log all s2s connections in a file"
home: "https://github.com/tpphu/ejabberd-contrib/tree/master/"
url: "git@github.com:tpphu/ejabberd-contrib.git"
