author: "Badlop <badlop at process-one.net>"
category: "stats"
summary: "Calculates and gathers statistics actively"
home: "https://github.com/tpphu/ejabberd-contrib/tree/master/"
url: "git@github.com:tpphu/ejabberd-contrib.git"
