author: "Badlop <badlop at process-one.net>"
category: "admin"
summary: "Execute scheduled commands"
home: "https://github.com/tpphu/ejabberd-contrib/tree/master/"
url: "git@github.com:tpphu/ejabberd-contrib.git"
